plugins {
    id 'java'
}

group = 'com.kodari'
version = '1.6.1'

java {
    toolchain.languageVersion = JavaLanguageVersion.of(17)
}

repositories {
    mavenCentral()
    maven { url = 'https://repo.papermc.io/repository/maven-public/' }
    maven { url = 'https://repo.extendedclip.com/releases/' }
}

dependencies {
    compileOnly 'io.papermc.paper:paper-api:1.20.4-R0.1-SNAPSHOT'
    compileOnly 'me.clip:placeholderapi:2.11.6'

    implementation 'com.github.cryptomorin:XSeries:11.2.0.1'
    implementation 'org.xerial:sqlite-jdbc:3.46.1.0'
    implementation 'org.mariadb.jdbc:mariadb-java-client:3.4.1'
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.release = 17
}

processResources {
    filesMatching('plugin.yml') {
        expand(version: project.version)
    }
}
