pluginManagement {
    repositories {
        gradlePluginPortal()
        maven { url = 'https://repo.papermc.io/repository/maven-public/' }
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        mavenCentral()
        maven { url = 'https://repo.papermc.io/repository/maven-public/' }
        maven { url = 'https://repo.extendedclip.com/releases/' }
    }
}

rootProject.name = 'Souls'
